using Microsoft.UI.Dispatching;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Automation;
using Microsoft.UI.Xaml.Controls;
using UniversalConverterX.Core.Utilities;

namespace UniversalConverterX.UI.Services;

public sealed record FfmpegCommandReviewRequest(int ProcessId, IReadOnlyList<string> Arguments);

public sealed record FfmpegCommandReviewResult(bool Approved, IReadOnlyList<string> Arguments, string? Error = null)
{
    public static FfmpegCommandReviewResult Cancelled() => new(false, []);
}

public interface IFfmpegCommandReviewService
{
    Task<FfmpegCommandReviewResult> ReviewAsync(
        FfmpegCommandReviewRequest request,
        CancellationToken cancellationToken);
}

/// <summary>
/// Serializes exact FFmpeg command reviews onto the WinUI dispatcher. Sidecar
/// jobs can run concurrently, but ContentDialog permits only one active dialog
/// per XamlRoot, so review requests intentionally queue.
/// </summary>
public sealed class FfmpegCommandReviewService : IFfmpegCommandReviewService
{
    private readonly DispatcherQueue _dispatcher;
    private readonly SemaphoreSlim _dialogGate = new(1, 1);

    public FfmpegCommandReviewService()
    {
        _dispatcher = DispatcherQueue.GetForCurrentThread()
            ?? throw new InvalidOperationException(
                "FFmpeg command review must be initialized on the WinUI dispatcher thread.");
    }

    public async Task<FfmpegCommandReviewResult> ReviewAsync(
        FfmpegCommandReviewRequest request,
        CancellationToken cancellationToken)
    {
        await _dialogGate.WaitAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            var completion = new TaskCompletionSource<FfmpegCommandReviewResult>(
                TaskCreationOptions.RunContinuationsAsynchronously);
            ContentDialog? activeDialog = null;
            using var registration = cancellationToken.Register(() =>
            {
                _dispatcher.TryEnqueue(() =>
                {
                    activeDialog?.Hide();
                    completion.TrySetCanceled(cancellationToken);
                });
            });

            if (!_dispatcher.TryEnqueue(async () =>
                {
                    try
                    {
                        activeDialog = BuildDialog(request, completion);
                        var result = await activeDialog.ShowAsync();
                        if (result != ContentDialogResult.Primary)
                            completion.TrySetResult(FfmpegCommandReviewResult.Cancelled());
                    }
                    catch (Exception exception)
                    {
                        completion.TrySetResult(new FfmpegCommandReviewResult(
                            false,
                            [],
                            $"FFmpeg command review failed: {exception.Message}"));
                    }
                }))
            {
                return new FfmpegCommandReviewResult(
                    false,
                    [],
                    "The WinUI dispatcher could not open FFmpeg command review.");
            }

            return await completion.Task.ConfigureAwait(false);
        }
        finally
        {
            _dialogGate.Release();
        }
    }

    private static ContentDialog BuildDialog(
        FfmpegCommandReviewRequest request,
        TaskCompletionSource<FfmpegCommandReviewResult> completion)
    {
        var commandBox = new TextBox
        {
            Header = "FFmpeg command",
            Text = FfmpegCommandTemplate.FormatCommand(request.Arguments),
            IsReadOnly = true,
            AcceptsReturn = true,
            TextWrapping = TextWrapping.Wrap,
            MinWidth = 620,
            MinHeight = 150,
            MaxHeight = 360,
        };
        ScrollViewer.SetVerticalScrollBarVisibility(commandBox, ScrollBarVisibility.Auto);
        AutomationProperties.SetAutomationId(commandBox, "FfmpegReviewCommandBox");

        var editToggle = new ToggleSwitch
        {
            Header = "Edit before run",
            OffContent = "Read-only generated command",
            OnContent = "Editing argument vector",
        };
        AutomationProperties.SetAutomationId(editToggle, "FfmpegReviewEditToggle");

        var status = new InfoBar
        {
            IsOpen = true,
            IsClosable = false,
            Severity = InfoBarSeverity.Informational,
            Title = "Generated by sidecar",
            Message = "Review the exact FFmpeg arguments. Turn on editing only when this invocation needs a manual override.",
        };
        AutomationProperties.SetAutomationId(status, "FfmpegReviewStatus");

        var stack = new StackPanel { Spacing = 12 };
        stack.Children.Add(new TextBlock
        {
            Text = $"Process {request.ProcessId} is waiting. Commands run as an argument vector without a shell.",
            TextWrapping = TextWrapping.Wrap,
        });
        stack.Children.Add(editToggle);
        stack.Children.Add(commandBox);
        stack.Children.Add(status);

        var root = (App.MainWindowHandle.Content as FrameworkElement)?.XamlRoot
            ?? throw new InvalidOperationException("The main window is not ready for command review.");
        var dialog = new ContentDialog
        {
            Title = "Advanced FFmpeg command",
            Content = stack,
            PrimaryButtonText = "Run",
            CloseButtonText = "Cancel",
            DefaultButton = ContentDialogButton.Primary,
            IsPrimaryButtonEnabled = true,
            XamlRoot = root,
        };

        void Validate()
        {
            if (!editToggle.IsOn)
            {
                dialog.IsPrimaryButtonEnabled = true;
                status.Severity = InfoBarSeverity.Informational;
                status.Title = "Generated by sidecar";
                status.Message = "The original generated argument vector will run unchanged.";
                return;
            }

            var valid = FfmpegCommandTemplate.TryParseReviewedCommand(
                commandBox.Text,
                request.Arguments,
                out _,
                out var error);
            dialog.IsPrimaryButtonEnabled = valid;
            status.Severity = valid ? InfoBarSeverity.Success : InfoBarSeverity.Error;
            status.Title = valid ? "Command accepted" : "Command blocked";
            status.Message = valid
                ? "The edited command is a valid shell-free argument vector."
                : error ?? "The edited command is invalid.";
        }

        editToggle.Toggled += (_, _) =>
        {
            commandBox.IsReadOnly = !editToggle.IsOn;
            Validate();
        };
        commandBox.TextChanged += (_, _) => Validate();
        dialog.PrimaryButtonClick += (_, eventArgs) =>
        {
            IReadOnlyList<string> arguments = request.Arguments;
            if (editToggle.IsOn)
            {
                if (!FfmpegCommandTemplate.TryParseReviewedCommand(
                        commandBox.Text,
                        request.Arguments,
                        out var reviewed,
                        out var error))
                {
                    eventArgs.Cancel = true;
                    status.Severity = InfoBarSeverity.Error;
                    status.Title = "Command blocked";
                    status.Message = error ?? "The edited command is invalid.";
                    return;
                }

                arguments = reviewed;
            }

            completion.TrySetResult(new FfmpegCommandReviewResult(true, arguments));
        };

        return dialog;
    }
}
